# -*- coding: utf-8 -*-
"""extract entity from image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOlcjCDCJT2FdonWb8wvsn7uscJiVBMS
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/nupursolanki3/Amazon-ML-Challenge-2024/refs/heads/main/train.csv")

df.head(10)

df.isnull().sum()

df['entity_name'].value_counts()

!apt-get install tessseract-ocr
!pip install pytesseract pillow requests

import requests
from PIL import Image
from io import BytesIO
import pytesseract

#image to OCR text conversion
#open the image
def load_image(url):
  response = requests.get(url)
  img = Image.open(BytesIO(response.content))
  return img

def get_text_from_image(img):
    text = pytesseract.image_to_string(img)
    return text

url = df.loc[0,'image_link']
img = load_image(url)
text = get_text_from_image(img)

print(text)
#it give us some random text from the image

img

!pip install easyocr

import easyocr
reader =  easyocr.Reader(['en'])
result = reader.readtext(url)

for r in result:
  print(r[1]) # read just the readable string

ocr_text_lines = [r[1] for r in result]
ocr_text = " ".join(ocr_text_lines)

print(ocr_text)

pattern = r'(\d+\.?\d*)\s*(g|kg)'

import re
matches = re.findall(pattern, ocr_text, flags=re.IGNORECASE)
print(matches)

if matches:
  value, unit = matches[0]
  entity_value = f"{value} {unit}"
  print(entity_value)
else:
  print("No match found")

#we could have gone for regression if we needed only the number but as we
#want unit as well we will go for classification



